baseURL = "https://tetov.se/"
languageCode = "en"
title = "tetov's blog"
theme = "tetov-kiss"
Paginate = 5
enableRobotsTXT = true

pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[params.assets]
customCSS = [ "css/custom.css" ]

[params.rss]
includeContent = true
authorName = "Anton T Johansson"
authorEmail = "anton@tetov.se"

[params.info]
enableSocial = true
homeTitle = "tetov's blog"
poweredby = false
related = false

[params.social]
twitter = "a_tetov"
github = "tetov"
email = "anton@tetov.se"
linkedin = "tetov"
instagram = "antontetov"
rss = "index.xml"

[params.sections_right]
"/about/" = "about"
"/pgp-key/" = "pgp key"
"/categories/portfolio/" = "portfolio"

[params.social.config]
platforms = ["twitter", "instagram", "email", "github", "linkedin", "rss"]

[permalinks]
posts = ":slug/"
pages = ":slug/"

[taxonomies]
category = "categories"
tag = "tags"

