baseURL = "https://blog.tetov.se"
languageCode = "en-us"
title = "Tetov's blog"
theme = "tetov-kiss"
Paginate = 5
enableRobotsTXT = true

pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[permalinks]
    post = ":slug/"
    note = ":slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params.assets]
    customCSS = [ "css/custom.css" ]

[params.info]
    enableSocial = true
    homeTitle = "Tetov's blog"
    related = false
    footerText = "<a href=\"https://tetov.se/\">portfolio</a> • <a href=\"/pages/pgp-key/\">pgp key</a>"

[params.social]
    twitter = "te_tov"
    github = "tetov"
    email = "anton@tetov.se"
    linkedin = "tetov"
    instagram = "antontetov"

[taxonomies]
tag = "tags"
